name: Rest Assured Java API Automation CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temirin'
          cache: maven

     
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Check build environment
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn -version
      - name: Execute tests
        run: mvn clean test

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs

      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
            name: TestNG Report
            path: target/reports/

