name: Rest Assured Java API Automation CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - uses: actions/checkout@v3

      - name: Check build environment
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn -version
      - name: Execute tests
        run: mvn clean test

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
            name: Maven Tests
            path: target/surefire-reports/*.xml
            reporter: java-junit
            fail-on-error: true


